### ISSUE TITLE
Support for GraalVM 21.2.0

### ISSUE THREAD

**Issue by jamesnetherton** [GoogleCloudPlatform/google-cloud-graalvm-support#180]
Seems there are some incompatibilities if you try to run the 0.4.0 release on GraalVM 21.2.0. It'd be nice if we can get a release that supports this version of GraalVM.

```
Fatal error:java.lang.NoSuchMethodError: 'void org.graalvm.nativeimage.impl.RuntimeReflectionSupport.register(boolean, boolean, java.lang.reflect.Field[])'
	at com.google.cloud.graalvm.features.NativeImageUtils.registerForUnsafeFieldAccess(NativeImageUtils.java:119)
	at com.google.cloud.graalvm.features.core.GrpcNettyFeature.loadMiscClasses(GrpcNettyFeature.java:125)
	at com.google.cloud.graalvm.features.core.GrpcNettyFeature.beforeAnalysis(GrpcNettyFeature.java:43)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$11(NativeImageGenerator.java:691)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:71)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:691)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:532)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:491)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:380)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:543)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:573)
```

**Comment by chanseokoh** [comment]
@dzou they [changed](https://github.com/oracle/graal/blob/release/graal-vm%2F21.2/sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/impl/ReflectionRegistry.java#L51) the method signature in 21.2.0. As the word `impl` in the package name implies, it seems like an internal package whose implementation may change between versions.

**Comment by dzou** [comment]
Thanks for the report @jamesnetherton. I actually ran into this too, and the fix has been committed to the PR in which we're trying to upgrade to 21.2.0: https://github.com/GoogleCloudPlatform/google-cloud-graalvm-support/pull/165

However we're stuck due to this issue which we think is a bug in GraalVM:  https://github.com/oracle/graal/issues/3629 
We get this weird null pointer exception in the compiler for one of our sample apps... Currently we're blocked from upgrading to 21.2.0 due to this issue.

**Comment by loicmathieu** [comment]
This will also impact Quarkus Google Cloud Services extensions as they plan to move to 21.2.0 asap.

Would it be possible to have a 0.5.0 "non final" version (snapshot or candidate release) to make it work while you sort things out with the GraalVM team ?

**Comment by dzou** [comment]
> This will also impact Quarkus Google Cloud Services extensions as they plan to move to 21.2.0 asap.
> 
> Would it be possible to have a 0.5.0 "non final" version (snapshot or candidate release) to make it work while you sort things out with the GraalVM team ?

Ok, let me do that then. I can release a 0.5.0 which has these patches by end of today.

**Comment by loicmathieu** [comment]
Thanks @dzou

**Comment by dzou** [comment]
Hey guys, I just released version `0.5.0` which should be compatible with GraalVM 21.2.0.

```
<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-graalvm-support</artifactId>
    <version>0.5.0</version>
</dependency>
```

I will keep an eye on https://github.com/oracle/graal/issues/3629 and followup if any updates are needed on our end. Please let me know if you also run into a related issue. I will keep this thread open as a place where we can discuss if needed.

**Comment by loicmathieu** [comment]
Thank you @dzou this fixes the issue with Quarkus Google Cloud Services extensions for Quarkus 2.2.

**Comment by dzou** [comment]
Gonna close this on our end. Based on what I'm seeing in the main issue there isn't anything we can really do here; will just have to wait for a fix upstream. It looks like the null pointer issue only affects the GCF functions framework library which does not affect the large majority of users.
