### ISSUE TITLE
Fatal error:com.oracle.svm.core.util.VMError$HostedError: Option name "TruffleMultiThreaded" ...

### ISSUE THREAD

**Issue by koduki** [GoogleCloudPlatform/google-cloud-graalvm-support#59]
Hi, I tried to build `quarkus-pubsub-sample` on my PC. But I had below error.

```bash
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 20.3.0 (Java Version 11.0.9+10-jvmci-20.3-b06)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] /home/koduki/.sdkman/candidates/java/20.3.0.r11-grl/bin/native-image -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Duser.language=en -J-Dfile.encoding=UTF-8 -H:+TraceClassInitialization --initialize-at-run-time=com.example.PubSubUtils --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -jar quarkus-pubsub-sample-0.2.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services -H:NativeLinkerOption=-no-pie --no-server -H:-UseServiceLoaderFeature -H:+StackTrace quarkus-pubsub-sample-0.2.0-SNAPSHOT-runner
Fatal error:com.oracle.svm.core.util.VMError$HostedError: Option name "TruffleMultiThreaded" has multiple definitions: com.oracle.svm.truffle.api.SubstrateTruffleOptions.TruffleMultiThreaded and com.oracle.svm.truffle.api.SubstateTruffleOptions.TruffleMultiThreaded
        at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
        at com.oracle.svm.hosted.option.HostedOptionParser.collectOptions(HostedOptionParser.java:89)
        at com.oracle.svm.hosted.option.HostedOptionParser.<init>(HostedOptionParser.java:62)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:238)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:509)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:115)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:541)
Error: Image build request failed with exit status 1
```

I tried below commands.

```bash
cd GoogleCloudPlatform/google-cloud-graalvm-support
mvn install
cd google-cloud-graalvm-samples/graalvm-samples-quarkus/ quarkus-pubsub-sample
mvn package -P graal
```

native-image and GraalVM version are below.
```bash
❯ native-image --version
GraalVM Version 20.3.0 (Java Version 11.0.9+10-jvmci-20.3-b06)
```

What should I do? Do you have any idea?

**Comment by dzou** [comment]
Thanks for the report @koduki - Will take a look. This may be related to https://github.com/GoogleCloudPlatform/google-cloud-graalvm-support/issues/58

**Comment by dzou** [comment]
Update: I think I found the solution for this. https://github.com/GoogleCloudPlatform/google-cloud-graalvm-support/pull/62 will fix this issue. 

The root problem is that because the library was marked as `compiled` scope, we were pulling in the GraalVM SDK for 20.2.0 but this would be incompatible with 20.3.0. Marking it as provided lets the compiler give us this dependency, so we are now flexible as to which GraalVM compiler version we support.

**Comment by dzou** [comment]
Hey @koduki -- I just submitted the fix. Can you try pulling in the latest version of the repo and running the Quarkus sample again? I think it should now work.

**Comment by koduki** [comment]
Sorry late response. Thank you! I try it.

**Comment by dzou** [comment]
Cool, sounds good. Let me know how it goes.

**Comment by koduki** [comment]
I could successfully compiled by the latest version. Thank you!

**Comment by dzou** [comment]
Thanks!
